import createClient from "openapi-fetch";
import type { paths } from "@guitarista/api-types";
import { env } from "@/lib/env";
import { ApiError } from "@/lib/api/problem";

/**
 * Typed FastAPI client. `paths` is regenerated by `pnpm gen:api` from the
 * backend's OpenAPI document.
 */
export const api = createClient<paths>({ baseUrl: env.NEXT_PUBLIC_API_URL });

export const API_PREFIX = "/api/v1";

/** Absolute URL for an API path (for `<a href>` downloads and EventSource). */
export function apiUrl(path: string, query?: Record<string, string | number | undefined>): string {
  const url = new URL(`${API_PREFIX}${path}`, env.NEXT_PUBLIC_API_URL);
  if (query) {
    for (const [k, v] of Object.entries(query)) {
      if (v !== undefined) url.searchParams.set(k, String(v));
    }
  }
  return url.toString();
}

interface FetchResult<T> {
  data?: T;
  error?: unknown;
  response: Response;
}

/** Turn an openapi-fetch result into data-or-throw (ApiError with problem+json details). */
export function unwrap<T>(result: FetchResult<T>): T {
  if (result.error !== undefined || !result.response.ok) {
    throw ApiError.fromResponse(result.response.status, result.error, result.response.statusText);
  }
  return result.data as T;
}

/** Multipart POST helper (openapi-fetch's multipart typing is awkward for `UploadFile`). */
export async function postMultipart<T>(path: string, file: File, field = "file"): Promise<T> {
  const form = new FormData();
  form.append(field, file, file.name);
  const response = await fetch(apiUrl(path), { method: "POST", body: form });
  const text = await response.text();
  let body: unknown = text;
  try {
    body = text ? JSON.parse(text) : null;
  } catch {
    // keep raw text
  }
  if (!response.ok) throw ApiError.fromResponse(response.status, body, response.statusText);
  return body as T;
}

