/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/uploads/score": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Score */
        post: operations["upload_score_api_v1_uploads_score_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/uploads/audio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Audio
         * @description Upload a recording (mp3/wav/m4a/flac/ogg, <= 50 MB) for the audio tier; pass the returned
         *     ``upload_id`` in ``POST /jobs``.
         */
        post: operations["upload_audio_api_v1_uploads_audio_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/score/tab": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Score To Tab */
        post: operations["score_to_tab_api_v1_score_tab_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/songs/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resolve Song
         * @description Resolve a link / typed text / title+artist into a Song (Spotify when configured).
         */
        post: operations["resolve_song_api_v1_songs_resolve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/songs/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Songs
         * @description Autocomplete via Spotify. Without credentials returns ``[]`` with ``X-Spotify: disabled``.
         */
        get: operations["search_songs_api_v1_songs_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/songs/{song_id}/candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Song Candidates
         * @description Browse every source's ranked candidates for a resolved song without starting a job.
         *
         *     Songsterr matches first (best score first), then Ultimate Guitar Tabs/Chords, then the single
         *     ``audio`` pseudo-candidate. ``tab_id`` is filled when a job already fetched that candidate.
         *     Pass a candidate to ``POST /jobs`` as ``candidate`` to fetch exactly it, or list the ones
         *     already tried in ``exclude``.
         */
        post: operations["song_candidates_api_v1_songs__song_id__candidates_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs_api_v1_jobs_get"];
        put?: never;
        /**
         * Create Job
         * @description Start a song→tab job. Poll ``GET /jobs/{id}`` or stream ``GET /jobs/{id}/events``.
         */
        post: operations["create_job_api_v1_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_v1_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Job */
        post: operations["cancel_job_api_v1_jobs__job_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Job Events
         * @description Server-sent events: replays the tier log, then streams ``tier``/``progress``/``done``/
         *     ``error`` events; a final ``end`` event closes the stream. Data is JSON (see ``JobEvent``).
         */
        get: operations["job_events_api_v1_jobs__job_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tabs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tabs */
        get: operations["list_tabs_api_v1_tabs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tabs/{tab_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Tab */
        get: operations["get_tab_api_v1_tabs__tab_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/spotify/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Spotify Login
         * @description Build the PKCE authorize URL; the client navigates to it.
         */
        get: operations["spotify_login_api_v1_spotify_login_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/spotify/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Spotify Status */
        get: operations["spotify_status_api_v1_spotify_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/spotify/auth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Spotify Disconnect
         * @description Forget the grant and stop any background prefetching.
         */
        delete: operations["spotify_disconnect_api_v1_spotify_auth_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Recommendations
         * @description The listening pool, best score first, without dismissed or unplayable entries.
         */
        get: operations["list_recommendations_api_v1_recommendations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recommendations/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh Recommendations
         * @description Rebuild the pool from Spotify right now (ignores the refresh interval).
         */
        post: operations["refresh_recommendations_api_v1_recommendations_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recommendations/{spotify_id}/dismiss": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Dismiss Recommendation
         * @description Hide one entry for good; a later refresh will not bring it back.
         */
        post: operations["dismiss_recommendation_api_v1_recommendations__spotify_id__dismiss_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recommendations/surprise": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Surprise
         * @description A score-weighted random ready tab; failing that, the best entry still to generate.
         */
        get: operations["surprise_api_v1_recommendations_surprise_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AudioUploadResponse */
        AudioUploadResponse: {
            /** Upload Id */
            upload_id: string;
            /** Filename */
            filename: string;
            /** Duration S */
            duration_s?: number | null;
            /** Sample Rate */
            sample_rate?: number | null;
        };
        /** Beat */
        Beat: {
            duration?: components["schemas"]["Duration"];
            /** Notes */
            notes?: components["schemas"]["Note"][];
            /** Chord Name */
            chord_name?: string | null;
            /** Text */
            text?: string | null;
            /** Tempo Bpm */
            tempo_bpm?: number | null;
        };
        /** Body_upload_audio_api_v1_uploads_audio_post */
        Body_upload_audio_api_v1_uploads_audio_post: {
            /** File */
            file: string;
        };
        /** Body_upload_score_api_v1_uploads_score_post */
        Body_upload_score_api_v1_uploads_score_post: {
            /** File */
            file: string;
        };
        /** Candidate */
        Candidate: {
            /**
             * Source
             * @enum {string}
             */
            source: "songsterr" | "ultimate_guitar" | "audio";
            /** External Id */
            external_id: string;
            /** Title */
            title: string;
            /** Artist */
            artist: string;
            /**
             * Score
             * @description Match score against the resolved song
             */
            score: number;
            /**
             * Kind
             * @description "Tabs" / "Chords" for UG; track-type summary for Songsterr
             */
            kind?: string | null;
            /** Rating */
            rating?: number | null;
            /** Votes */
            votes?: number | null;
            /** Track Count */
            track_count?: number | null;
            /** Url */
            url?: string | null;
            /**
             * Tab Id
             * @description An already fetched tab for this candidate and song, if any
             */
            tab_id?: string | null;
            /**
             * Available
             * @default true
             */
            available: boolean;
            /**
             * Reason
             * @description Why the candidate is unavailable
             */
            reason?: string | null;
        };
        /**
         * CandidateRef
         * @description Points at one browsable candidate: a Songsterr ``songId``, a UG tab id, or ``"audio"``.
         */
        CandidateRef: {
            /**
             * Source
             * @enum {string}
             */
            source: "songsterr" | "ultimate_guitar" | "audio";
            /** External Id */
            external_id: string;
        };
        /** CandidatesRequest */
        CandidatesRequest: {
            /**
             * Limit
             * @description Max candidates per source
             * @default 10
             */
            limit: number;
        };
        /** CandidatesResponse */
        CandidatesResponse: {
            /** Song Id */
            song_id: string;
            /** Candidates */
            candidates: components["schemas"]["Candidate"][];
            /**
             * Warnings
             * @description Sources that failed or were disabled
             */
            warnings?: string[];
        };
        /**
         * Duration
         * @description Note value as a fraction of a whole note, e.g. num=1, den=4 is a quarter.
         */
        Duration: {
            /**
             * Num
             * @default 1
             */
            num: number;
            /**
             * Den
             * @default 4
             */
            den: number;
            /**
             * Dots
             * @default 0
             */
            dots: number;
            /** Tuplet */
            tuplet?: [
                number,
                number
            ] | null;
        };
        /**
         * Evidence
         * @description Where a track showed up in the user's history (ranks are 0-based, best first).
         */
        Evidence: {
            /**
             * Top Short
             * @description Rank in top tracks, last 4 weeks
             */
            top_short?: number | null;
            /**
             * Top Medium
             * @description Rank in top tracks, last 6 months
             */
            top_medium?: number | null;
            /**
             * Top Long
             * @description Rank in top tracks, all time
             */
            top_long?: number | null;
            /**
             * Recent
             * @description Plays in the recently-played window
             * @default 0
             */
            recent: number;
            /**
             * Liked
             * @description Present in the user's saved tracks
             * @default false
             */
            liked: boolean;
        };
        /** Features */
        Features: {
            /** Spotify */
            spotify: boolean;
            /**
             * Spotify User
             * @description Spotify client id configured, so PKCE login is possible
             * @default false
             */
            spotify_user: boolean;
            /**
             * Spotify Connected
             * @description A Spotify user grant is stored (noodle mode can read history)
             * @default false
             */
            spotify_connected: boolean;
            /** Llm */
            llm: boolean;
            /** Songsterr */
            songsterr: boolean;
            /** Ug */
            ug: boolean;
            /** Audio */
            audio: boolean;
            /** Ytdlp */
            ytdlp: boolean;
            /** Separation */
            separation: boolean;
            /**
             * Ml Sidecar Ok
             * @description guitarista-ml sidecar responds to `probe` with basic-pitch
             * @default false
             */
            ml_sidecar_ok: boolean;
            /**
             * Separation Available
             * @description Demucs installed in the sidecar (uv sync --extra separate)
             * @default false
             */
            separation_available: boolean;
            /**
             * Tabcnn Available
             * @description TabCNN ONNX weights present in the sidecar (string/fret transcription)
             * @default false
             */
            tabcnn_available: boolean;
            /**
             * Audio Model
             * @description Transcriber the audio tier uses
             * @default basic-pitch
             */
            audio_model: string;
            /**
             * Jobs
             * @description POST /jobs + SSE job pipeline available
             * @default true
             */
            jobs: boolean;
            /**
             * Musescore
             * @description MuseScore binary found; enables .mscz / Guitar Pro / Capella score uploads
             * @default false
             */
            musescore: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /** Status */
            status: string;
            /** Version */
            version: string;
            features: components["schemas"]["Features"];
            /** Ffmpeg */
            ffmpeg: boolean;
            /**
             * Ytdlp
             * @description yt-dlp binary found on PATH
             * @default false
             */
            ytdlp: boolean;
            /**
             * Tiers
             * @description Tab sources in fallback order
             */
            tiers?: string[];
            /**
             * Running Jobs
             * @default 0
             */
            running_jobs: number;
        };
        /** Job */
        Job: {
            /** Id */
            id?: string;
            /**
             * Status
             * @default queued
             * @enum {string}
             */
            status: "queued" | "running" | "done" | "failed" | "cancelled" | "interrupted";
            request: components["schemas"]["TabRequest"];
            /** Song Id */
            song_id?: string | null;
            /** Tab Id */
            tab_id?: string | null;
            /** Tiers */
            tiers?: components["schemas"]["TierLogEntry"][];
            /**
             * Progress
             * @default 0
             */
            progress: number;
            /** Error */
            error?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at?: string;
        };
        /** LoginResponse */
        LoginResponse: {
            /**
             * Authorize Url
             * @description Send the browser here to grant access
             */
            authorize_url: string;
            /** Scopes */
            scopes?: string[];
        };
        /** Measure */
        Measure: {
            /** Number */
            number: number;
            time_signature?: components["schemas"]["TimeSignature"] | null;
            /** Voices */
            voices?: components["schemas"]["Voice"][];
            /** Marker */
            marker?: string | null;
            /**
             * Repeat Start
             * @default false
             */
            repeat_start: boolean;
            /** Repeat End */
            repeat_end?: number | null;
        };
        /** Note */
        Note: {
            /**
             * String
             * @description 1 = highest-pitched string
             */
            string: number;
            /** Fret */
            fret: number;
            /** Pitch Midi */
            pitch_midi?: number | null;
            /**
             * Tie
             * @default false
             */
            tie: boolean;
            /**
             * Dead
             * @default false
             */
            dead: boolean;
            /**
             * Ghost
             * @default false
             */
            ghost: boolean;
            /** Tech */
            tech?: string[];
            /**
             * Finger
             * @description 0 thumb, 1 index .. 4 pinky
             */
            finger?: number | null;
        };
        /**
         * PoolEntry
         * @description One candidate song for noodling, as stored in ``listening_pool``.
         */
        PoolEntry: {
            /** Spotify Id */
            spotify_id: string;
            /** Title */
            title: string;
            /** Artist */
            artist: string;
            /** Album */
            album?: string | null;
            /** Artwork Url */
            artwork_url?: string | null;
            /** Duration Ms */
            duration_ms?: number | null;
            evidence?: components["schemas"]["Evidence"];
            /**
             * Score
             * @default 0
             */
            score: number;
            /**
             * Availability
             * @default unknown
             * @enum {string}
             */
            availability: "unknown" | "available" | "unavailable";
            /** @description Songsterr candidate a prefetch job can target directly */
            candidate?: components["schemas"]["Candidate"] | null;
            /** Song Id */
            song_id?: string | null;
            /** Tab Id */
            tab_id?: string | null;
            /** Job Id */
            job_id?: string | null;
            /**
             * Status
             * @default new
             * @enum {string}
             */
            status: "new" | "checking" | "queued" | "ready" | "failed" | "dismissed";
            /** Error */
            error?: string | null;
            /**
             * Attempts
             * @default 0
             */
            attempts: number;
            /** Refreshed At */
            refreshed_at?: string | null;
        };
        /**
         * PoolSummary
         * @description What one :func:`build_pool` run did.
         */
        PoolSummary: {
            /**
             * Fetched
             * @description Distinct tracks seen across all endpoints
             * @default 0
             */
            fetched: number;
            /**
             * New
             * @description Entries that were not in the pool before
             * @default 0
             */
            new: number;
            /**
             * Available
             * @description Entries confirmed playable this run
             * @default 0
             */
            available: number;
            /**
             * Ready
             * @description Entries that already have a tab in the library
             * @default 0
             */
            ready: number;
            /**
             * Skipped
             * @description Pool was still fresh, nothing was fetched
             * @default false
             */
            skipped: boolean;
            /**
             * Errors
             * @description Endpoints that failed
             */
            errors?: string[];
        };
        /** ScorePart */
        ScorePart: {
            /** Index */
            index: number;
            /** Name */
            name: string;
            /** Note Count */
            note_count: number;
            /** Pitch Range */
            pitch_range?: [
                number,
                number
            ] | null;
        };
        /** ScoreTabRequest */
        ScoreTabRequest: {
            /** Upload Id */
            upload_id: string;
            /**
             * Part Index
             * @default 0
             */
            part_index: number;
            /** Tuning */
            tuning?: number[] | null;
            /**
             * Capo
             * @default 0
             */
            capo: number;
            /**
             * Max Fret
             * @default 15
             */
            max_fret: number;
            /**
             * Out Of Range
             * @default raise
             * @enum {string}
             */
            out_of_range: "raise" | "drop" | "octave_shift";
            /**
             * Cost Profile
             * @description 'tabgen' classic heuristics, 'lead' stays in position instead of jumping to open strings, 'beginner' favours open strings and low frets
             * @default tabgen
             * @enum {string}
             */
            cost_profile: "tabgen" | "lead" | "beginner";
        };
        /** ScoreUploadResponse */
        ScoreUploadResponse: {
            /** Upload Id */
            upload_id: string;
            /** Filename */
            filename: string;
            /** Title */
            title?: string | null;
            /** Artist */
            artist?: string | null;
            /** Parts */
            parts: components["schemas"]["ScorePart"][];
        };
        /** Song */
        Song: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Artist */
            artist: string;
            /** Album */
            album?: string | null;
            /** Duration S */
            duration_s?: number | null;
            /** Spotify Id */
            spotify_id?: string | null;
            /** Isrc */
            isrc?: string | null;
            /** Artwork Url */
            artwork_url?: string | null;
            /**
             * Normalized Query
             * @description Normalized '<artist> <title>' used for search and dedupe
             * @default
             */
            normalized_query: string;
        };
        /**
         * SongQuery
         * @description What the user typed or pasted; at least one of the fields is expected.
         */
        SongQuery: {
            /** Raw */
            raw?: string | null;
            /** Spotify Url */
            spotify_url?: string | null;
            /** Title */
            title?: string | null;
            /** Artist */
            artist?: string | null;
        };
        /**
         * SpotifyStatus
         * @description Answer to ``GET /spotify/status``.
         */
        SpotifyStatus: {
            /**
             * Connected
             * @default false
             */
            connected: boolean;
            /** Display Name */
            display_name?: string | null;
            /** Spotify User Id */
            spotify_user_id?: string | null;
            /** Scopes */
            scopes?: string[];
            /** Expires At */
            expires_at?: string | null;
            /**
             * Configured
             * @description A Spotify client id is set, so login is possible
             * @default false
             */
            configured: boolean;
        };
        /**
         * SurprisePick
         * @description A single pool entry chosen at random (score-weighted) for the Surprise me button.
         */
        SurprisePick: {
            entry: components["schemas"]["PoolEntry"];
            /**
             * Tab Id
             * @description Ready tab to open; null means the client should start a job
             */
            tab_id?: string | null;
            /**
             * Reason
             * @description Human label for why this was picked
             */
            reason?: string | null;
        };
        /** Tab */
        Tab: {
            /** Id */
            id?: string;
            /** Song Id */
            song_id?: string | null;
            /**
             * Title
             * @default Untitled
             */
            title: string;
            /** Artist */
            artist?: string | null;
            /** @default manual */
            source: components["schemas"]["TabSourceKind"];
            /** Source Ref */
            source_ref?: string | null;
            /**
             * Confidence
             * @default 1
             */
            confidence: number;
            /**
             * Tempo Bpm
             * @default 120
             */
            tempo_bpm: number;
            time_signature?: components["schemas"]["TimeSignature"];
            /** Tracks */
            tracks?: components["schemas"]["Track"][];
            /** Warnings */
            warnings?: string[];
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
        };
        /**
         * TabRequest
         * @description Body of ``POST /jobs``: ``song`` (link / text / title+artist), ``song_id`` (an already
         *     resolved song) and/or ``upload_id``. ``candidate`` fetches exactly one browsed candidate;
         *     ``exclude`` makes every tier skip the listed candidates before picking ("not this one, next").
         *     ``origin`` marks background "noodle" prefetch jobs (from the Spotify listening pool) so the
         *     UI can tell them apart from jobs the user asked for explicitly.
         */
        TabRequest: {
            song?: components["schemas"]["SongQuery"] | null;
            /**
             * Song Id
             * @description Reuse an already resolved song (from /songs/resolve or a job)
             */
            song_id?: string | null;
            /** Upload Id */
            upload_id?: string | null;
            /**
             * Audio Url
             * @description Exact media URL for the audio tier to download with yt-dlp, instead of searching. Ignored when upload_id is set; still requires GUITARISTA_ENABLE_YTDLP.
             */
            audio_url?: string | null;
            /** @description Fetch exactly this candidate; only its source runs and nothing is ranked */
            candidate?: components["schemas"]["CandidateRef"] | null;
            /**
             * Exclude
             * @description Candidates every tier must skip before picking
             */
            exclude?: components["schemas"]["CandidateRef"][];
            /** Tuning */
            tuning?: number[] | null;
            /**
             * Capo
             * @default 0
             */
            capo: number;
            /**
             * Max Fret
             * @description Highest fret the solver may use (audio tier)
             */
            max_fret?: number | null;
            /**
             * Cost Profile
             * @description Fretting preference for the solver (audio tier): 'tabgen' classic heuristics, 'lead' stays in position instead of jumping to open strings, 'beginner' favours open strings and low frets
             * @default tabgen
             * @enum {string}
             */
            cost_profile: "tabgen" | "lead" | "beginner";
            /**
             * Tiers
             * @description Restrict to these tiers (default: all enabled, in order)
             */
            tiers?: ("resolve" | "songsterr" | "ultimate_guitar" | "audio")[] | null;
            /**
             * Origin
             * @description Who asked for this job: 'user' for an explicit request, 'noodle' for a background prefetch job started from the Spotify listening pool, so the UI can tell them apart
             * @default user
             * @enum {string}
             */
            origin: "user" | "noodle";
        };
        /**
         * TabSourceKind
         * @enum {string}
         */
        TabSourceKind: "songsterr" | "ultimate_guitar" | "audio" | "score" | "manual";
        /** TabSummary */
        TabSummary: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Artist */
            artist: string | null;
            /** Source */
            source: string;
            /** Confidence */
            confidence: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Song Id */
            song_id?: string | null;
            /** Track Count */
            track_count: number;
        };
        /** TierLogEntry */
        TierLogEntry: {
            /**
             * Tier
             * @enum {string}
             */
            tier: "resolve" | "songsterr" | "ultimate_guitar" | "audio";
            /**
             * Status
             * @default pending
             * @enum {string}
             */
            status: "pending" | "skipped" | "running" | "success" | "failed" | "timeout" | "cancelled";
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /** Message */
            message?: string | null;
            /** Detail */
            detail?: {
                [key: string]: unknown;
            };
        };
        /** TimeSignature */
        TimeSignature: {
            /**
             * Numerator
             * @default 4
             */
            numerator: number;
            /**
             * Denominator
             * @default 4
             */
            denominator: number;
        };
        /** Track */
        Track: {
            /**
             * Name
             * @default Guitar
             */
            name: string;
            /**
             * Instrument
             * @default acoustic_guitar_steel
             */
            instrument: string;
            /**
             * Tuning
             * @description MIDI pitch of open strings, string 1..N (highest first)
             */
            tuning?: number[];
            /**
             * Capo
             * @default 0
             */
            capo: number;
            /** Measures */
            measures?: components["schemas"]["Measure"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** Voice */
        Voice: {
            /** Beats */
            beats?: components["schemas"]["Beat"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    upload_score_api_v1_uploads_score_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_score_api_v1_uploads_score_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScoreUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_audio_api_v1_uploads_audio_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_audio_api_v1_uploads_audio_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AudioUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    score_to_tab_api_v1_score_tab_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScoreTabRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tab"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_song_api_v1_songs_resolve_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SongQuery"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Song"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_songs_api_v1_songs_search_get: {
        parameters: {
            query: {
                q: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Song"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    song_candidates_api_v1_songs__song_id__candidates_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                song_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CandidatesRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidatesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_api_v1_jobs_get: {
        parameters: {
            query?: {
                limit?: number;
                status?: ("queued" | "running" | "done" | "failed" | "cancelled" | "interrupted") | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_job_api_v1_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TabRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_v1_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_job_api_v1_jobs__job_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    job_events_api_v1_jobs__job_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tabs_api_v1_tabs_get: {
        parameters: {
            query?: {
                limit?: number;
                /** @description Only tabs for this song */
                song_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TabSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_tab_api_v1_tabs__tab_id__get: {
        parameters: {
            query?: {
                format?: "json" | "alphatex" | "musicxml" | "ascii";
                track?: number;
            };
            header?: never;
            path: {
                tab_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tab"];
                    "text/x-alphatex": unknown;
                    "text/plain": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    spotify_login_api_v1_spotify_login_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
        };
    };
    spotify_status_api_v1_spotify_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpotifyStatus"];
                };
            };
        };
    };
    spotify_disconnect_api_v1_spotify_auth_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_recommendations_api_v1_recommendations_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PoolEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_recommendations_api_v1_recommendations_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PoolSummary"];
                };
            };
        };
    };
    dismiss_recommendation_api_v1_recommendations__spotify_id__dismiss_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                spotify_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    surprise_api_v1_recommendations_surprise_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SurprisePick"];
                };
            };
        };
    };
}
